<?xml version="1.0" encoding="UTF-8"?>
<testsuites timestamp="2023-06-28T15:05:14.157" time="40.638" tests="15" skipped="0" failures="10" errors="1">
<testsuite name="test/testfiles/_retry_tests.jl" timestamp="2023-06-28T15:05:14.157" time="40.638" tests="15" skipped="0" failures="10" errors="1">
	<testcase name="Pass on second run" timestamp="2023-06-28T15:05:14.157" time="0.105" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0xbb7458bbdb65692e"></property>
		<property name="dd_tags[perf.bytes]" value="2476178"></property>
		<property name="dd_tags[perf.allocs]" value="40391"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.029235457"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.003822085000000003"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:17">Error in testset "Pass on second run" on worker 39388:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:17
  Expression: x
Captured logs for test setup "StatefulSetup" (dependency of "Pass on second run") at test/testfiles/_retry_tests.jl:1 on worker 39388
These are the test setup logs.
No Captured Logs for test item "Pass on second run" at test/testfiles/_retry_tests.jl:12 on worker 39388
		</error>
	</testcase>
	<testcase name="Pass on second run" timestamp="2023-06-28T15:05:14.409" time="0.002" tests="1" skipped="0" failures="0" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0xbb7458bbdb65692e"></property>
		<property name="dd_tags[perf.bytes]" value="79510"></property>
		<property name="dd_tags[perf.allocs]" value="1227"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="1.67e-7"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.0022519579999999997"></property>
		</properties>
	</testcase>
	<testcase name="Error, then Fail, then Pass" timestamp="2023-06-28T15:05:14.411" time="0.437" tests="1" skipped="0" failures="0" errors="1">
		<properties>
		<property name="dd_tags[test.id]" value="0x72e8f30d618e9a42"></property>
		<property name="dd_tags[perf.bytes]" value="72680682"></property>
		<property name="dd_tags[perf.allocs]" value="1352076"></property>
		<property name="dd_tags[perf.gctime]" value="0.004997083"></property>
		<property name="dd_tags[perf.compile_time]" value="0.367770125"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.06458583299999998"></property>
		</properties>
		<error message="Error during test at test/testfiles/_retry_tests.jl:26">Error in testset "Error, then Fail, then Pass" on worker 39388:
Error During Test at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:26
  Test threw exception
  Expression: not_defined_err
  UndefVarError: not_defined_err not defined
  Stacktrace:
   [1] macro expansion
     @ /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Test/src/Test.jl:464 [inlined]
   [2] top-level scope
     @ /repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:26
Captured logs for test setup "StatefulSetup" (dependency of "Error, then Fail, then Pass") at test/testfiles/_retry_tests.jl:1 on worker 39388
These are the test setup logs.
Captured Logs for test item "Error, then Fail, then Pass" at test/testfiles/_retry_tests.jl:20 on worker 39388
These are the logs for run number: 1
		</error>
	</testcase>
	<testcase name="Error, then Fail, then Pass" timestamp="2023-06-28T15:05:14.908" time="0.008" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0x72e8f30d618e9a42"></property>
		<property name="dd_tags[perf.bytes]" value="216435"></property>
		<property name="dd_tags[perf.allocs]" value="3704"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.005009625"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.0033981659999999993"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:28">Error in testset "Error, then Fail, then Pass" on worker 39388:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:28
  Expression: 2 + 2 == 5
   Evaluated: 4 == 5
Captured logs for test setup "StatefulSetup" (dependency of "Error, then Fail, then Pass") at test/testfiles/_retry_tests.jl:1 on worker 39388
These are the test setup logs.
Captured Logs for test item "Error, then Fail, then Pass" at test/testfiles/_retry_tests.jl:20 on worker 39388
These are the logs for run number: 2
		</error>
	</testcase>
	<testcase name="Error, then Fail, then Pass" timestamp="2023-06-28T15:05:14.965" time="0.004" tests="1" skipped="0" failures="0" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0x72e8f30d618e9a42"></property>
		<property name="dd_tags[perf.bytes]" value="103902"></property>
		<property name="dd_tags[perf.allocs]" value="1709"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="4.1e-8"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.003528209"></property>
		</properties>
	</testcase>
	<testcase name="Has retries=4 and always fails" timestamp="2023-06-28T15:05:14.969" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0xf20c917170a2fef9"></property>
		<property name="dd_tags[perf.bytes]" value="76694"></property>
		<property name="dd_tags[perf.allocs]" value="1171"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="1.25e-7"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.0018379590000000001"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:37">Error in testset "Has retries=4 and always fails" on worker 39388:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:37
  Expression: false
Captured logs for test setup "StatefulSetup" (dependency of "Has retries=4 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 39388
These are the test setup logs.
No Captured Logs for test item "Has retries=4 and always fails" at test/testfiles/_retry_tests.jl:34 on worker 39388
		</error>
	</testcase>
	<testcase name="Has retries=4 and always fails" timestamp="2023-06-28T15:05:15.019" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0xf20c917170a2fef9"></property>
		<property name="dd_tags[perf.bytes]" value="76694"></property>
		<property name="dd_tags[perf.allocs]" value="1171"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.0"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.002027375"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:37">Error in testset "Has retries=4 and always fails" on worker 39388:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:37
  Expression: false
Captured logs for test setup "StatefulSetup" (dependency of "Has retries=4 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 39388
These are the test setup logs.
No Captured Logs for test item "Has retries=4 and always fails" at test/testfiles/_retry_tests.jl:34 on worker 39388
		</error>
	</testcase>
	<testcase name="Has retries=4 and always fails" timestamp="2023-06-28T15:05:15.069" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0xf20c917170a2fef9"></property>
		<property name="dd_tags[perf.bytes]" value="76694"></property>
		<property name="dd_tags[perf.allocs]" value="1171"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="8.4e-8"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.002022458"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:37">Error in testset "Has retries=4 and always fails" on worker 39388:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:37
  Expression: false
Captured logs for test setup "StatefulSetup" (dependency of "Has retries=4 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 39388
These are the test setup logs.
No Captured Logs for test item "Has retries=4 and always fails" at test/testfiles/_retry_tests.jl:34 on worker 39388
		</error>
	</testcase>
	<testcase name="Has retries=4 and always fails" timestamp="2023-06-28T15:05:15.119" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0xf20c917170a2fef9"></property>
		<property name="dd_tags[perf.bytes]" value="76694"></property>
		<property name="dd_tags[perf.allocs]" value="1171"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="4.2e-8"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.00203025"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:37">Error in testset "Has retries=4 and always fails" on worker 39388:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:37
  Expression: false
Captured logs for test setup "StatefulSetup" (dependency of "Has retries=4 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 39388
These are the test setup logs.
No Captured Logs for test item "Has retries=4 and always fails" at test/testfiles/_retry_tests.jl:34 on worker 39388
		</error>
	</testcase>
	<testcase name="Has retries=4 and always fails" timestamp="2023-06-28T15:05:15.169" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0xf20c917170a2fef9"></property>
		<property name="dd_tags[perf.bytes]" value="76694"></property>
		<property name="dd_tags[perf.allocs]" value="1171"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.0"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.002135"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:37">Error in testset "Has retries=4 and always fails" on worker 39388:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:37
  Expression: false
Captured logs for test setup "StatefulSetup" (dependency of "Has retries=4 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 39388
These are the test setup logs.
No Captured Logs for test item "Has retries=4 and always fails" at test/testfiles/_retry_tests.jl:34 on worker 39388
		</error>
	</testcase>
	<testcase name="Has retries=1 and always fails" timestamp="2023-06-28T15:05:15.172" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0x25de935b67efc82c"></property>
		<property name="dd_tags[perf.bytes]" value="76694"></property>
		<property name="dd_tags[perf.allocs]" value="1171"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.0"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.00193375"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:43">Error in testset "Has retries=1 and always fails" on worker 39388:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:43
  Expression: false
Captured logs for test setup "StatefulSetup" (dependency of "Has retries=1 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 39388
These are the test setup logs.
No Captured Logs for test item "Has retries=1 and always fails" at test/testfiles/_retry_tests.jl:40 on worker 39388
		</error>
	</testcase>
	<testcase name="Has retries=1 and always fails" timestamp="2023-06-28T15:05:15.222" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0x25de935b67efc82c"></property>
		<property name="dd_tags[perf.bytes]" value="76694"></property>
		<property name="dd_tags[perf.allocs]" value="1171"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="2.5e-7"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.002077291"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:43">Error in testset "Has retries=1 and always fails" on worker 39388:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:43
  Expression: false
Captured logs for test setup "StatefulSetup" (dependency of "Has retries=1 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 39388
These are the test setup logs.
No Captured Logs for test item "Has retries=1 and always fails" at test/testfiles/_retry_tests.jl:40 on worker 39388
		</error>
	</testcase>
	<testcase name="Has retries=1 and always fails" timestamp="2023-06-28T15:05:15.272" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0x25de935b67efc82c"></property>
		<property name="dd_tags[perf.bytes]" value="76694"></property>
		<property name="dd_tags[perf.allocs]" value="1171"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="4.2e-8"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.002062249"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:43">Error in testset "Has retries=1 and always fails" on worker 39388:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:43
  Expression: false
Captured logs for test setup "StatefulSetup" (dependency of "Has retries=1 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 39388
These are the test setup logs.
No Captured Logs for test item "Has retries=1 and always fails" at test/testfiles/_retry_tests.jl:40 on worker 39388
		</error>
	</testcase>
	<testcase name="Timeout always" timestamp="2023-06-28T15:05:15.275" time="20.013" tests="1" skipped="0" failures="0" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0x7b956facd518e1d5"></property>
		<property name="dd_tags[perf.bytes]" value="487748"></property>
		<property name="dd_tags[perf.allocs]" value="8937"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.006330126"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="20.007054291"></property>
		</properties>
	</testcase>
	<testcase name="Timeout first, pass after" timestamp="2023-06-28T15:05:35.294" time="20.052" tests="1" skipped="0" failures="0" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0x3f7f2ce4e7b99b11"></property>
		<property name="dd_tags[perf.bytes]" value="3373762"></property>
		<property name="dd_tags[perf.allocs]" value="59584"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.035113916"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="20.016683876"></property>
		</properties>
	</testcase>
</testsuite>
</testsuites>