<?xml version="1.0" encoding="UTF-8"?>
<testsuites timestamp="2023-06-28T15:27:19.367" time="40.66" tests="15" skipped="0" failures="10" errors="1">
<testsuite name="test/testfiles/_retry_tests.jl" timestamp="2023-06-28T15:27:19.367" time="40.66" tests="15" skipped="0" failures="10" errors="1">
	<testcase name="Pass on second run" timestamp="2023-06-28T15:27:19.367" time="0.112" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0x2fd34d21eb2dbad0"></property>
		<property name="dd_tags[perf.bytes]" value="2475842"></property>
		<property name="dd_tags[perf.allocs]" value="40390"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.031056791"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.002981042000000003"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:17">Error in testset "Pass on second run" on worker 70762:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:17
  Expression: x
Captured logs for test setup "StatefulSetup" (dependency of "Pass on second run") at test/testfiles/_retry_tests.jl:1 on worker 70762
These are the test setup logs.
No Captured Logs for test item "Pass on second run" at test/testfiles/_retry_tests.jl:12 on worker 70762
		</error>
	</testcase>
	<testcase name="Pass on second run" timestamp="2023-06-28T15:27:19.629" time="0.002" tests="1" skipped="0" failures="0" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0x2fd34d21eb2dbad0"></property>
		<property name="dd_tags[perf.bytes]" value="79510"></property>
		<property name="dd_tags[perf.allocs]" value="1227"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="8.3e-8"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.002276083"></property>
		</properties>
	</testcase>
	<testcase name="Error, then Fail, then Pass" timestamp="2023-06-28T15:27:19.632" time="0.453" tests="1" skipped="0" failures="0" errors="1">
		<properties>
		<property name="dd_tags[test.id]" value="0x7abbf01f0a34efc6"></property>
		<property name="dd_tags[perf.bytes]" value="72680682"></property>
		<property name="dd_tags[perf.allocs]" value="1352076"></property>
		<property name="dd_tags[perf.gctime]" value="0.005557459"></property>
		<property name="dd_tags[perf.compile_time]" value="0.383623833"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.06336304100000001"></property>
		</properties>
		<error message="Error during test at test/testfiles/_retry_tests.jl:26">Error in testset "Error, then Fail, then Pass" on worker 70762:
Error During Test at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:26
  Test threw exception
  Expression: not_defined_err
  UndefVarError: not_defined_err not defined
  Stacktrace:
   [1] macro expansion
     @ /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Test/src/Test.jl:464 [inlined]
   [2] top-level scope
     @ /repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:26
Captured logs for test setup "StatefulSetup" (dependency of "Error, then Fail, then Pass") at test/testfiles/_retry_tests.jl:1 on worker 70762
These are the test setup logs.
Captured Logs for test item "Error, then Fail, then Pass" at test/testfiles/_retry_tests.jl:20 on worker 70762
These are the logs for run number: 1
		</error>
	</testcase>
	<testcase name="Error, then Fail, then Pass" timestamp="2023-06-28T15:27:20.144" time="0.009" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0x7abbf01f0a34efc6"></property>
		<property name="dd_tags[perf.bytes]" value="216435"></property>
		<property name="dd_tags[perf.allocs]" value="3704"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.005114542"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.003405374000000001"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:28">Error in testset "Error, then Fail, then Pass" on worker 70762:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:28
  Expression: 2 + 2 == 5
   Evaluated: 4 == 5
Captured logs for test setup "StatefulSetup" (dependency of "Error, then Fail, then Pass") at test/testfiles/_retry_tests.jl:1 on worker 70762
These are the test setup logs.
Captured Logs for test item "Error, then Fail, then Pass" at test/testfiles/_retry_tests.jl:20 on worker 70762
These are the logs for run number: 2
		</error>
	</testcase>
	<testcase name="Error, then Fail, then Pass" timestamp="2023-06-28T15:27:20.204" time="0.003" tests="1" skipped="0" failures="0" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0x7abbf01f0a34efc6"></property>
		<property name="dd_tags[perf.bytes]" value="103902"></property>
		<property name="dd_tags[perf.allocs]" value="1709"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="4.2e-8"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.003453791"></property>
		</properties>
	</testcase>
	<testcase name="Has retries=4 and always fails" timestamp="2023-06-28T15:27:20.207" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0x1f0aa0c1646351f8"></property>
		<property name="dd_tags[perf.bytes]" value="76694"></property>
		<property name="dd_tags[perf.allocs]" value="1171"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="4.2e-8"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.0018109579999999999"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:37">Error in testset "Has retries=4 and always fails" on worker 70762:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:37
  Expression: false
Captured logs for test setup "StatefulSetup" (dependency of "Has retries=4 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 70762
These are the test setup logs.
No Captured Logs for test item "Has retries=4 and always fails" at test/testfiles/_retry_tests.jl:34 on worker 70762
		</error>
	</testcase>
	<testcase name="Has retries=4 and always fails" timestamp="2023-06-28T15:27:20.258" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0x1f0aa0c1646351f8"></property>
		<property name="dd_tags[perf.bytes]" value="76694"></property>
		<property name="dd_tags[perf.allocs]" value="1171"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="4.1e-8"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.002061667"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:37">Error in testset "Has retries=4 and always fails" on worker 70762:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:37
  Expression: false
Captured logs for test setup "StatefulSetup" (dependency of "Has retries=4 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 70762
These are the test setup logs.
No Captured Logs for test item "Has retries=4 and always fails" at test/testfiles/_retry_tests.jl:34 on worker 70762
		</error>
	</testcase>
	<testcase name="Has retries=4 and always fails" timestamp="2023-06-28T15:27:20.308" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0x1f0aa0c1646351f8"></property>
		<property name="dd_tags[perf.bytes]" value="76694"></property>
		<property name="dd_tags[perf.allocs]" value="1171"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.0"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.002077167"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:37">Error in testset "Has retries=4 and always fails" on worker 70762:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:37
  Expression: false
Captured logs for test setup "StatefulSetup" (dependency of "Has retries=4 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 70762
These are the test setup logs.
No Captured Logs for test item "Has retries=4 and always fails" at test/testfiles/_retry_tests.jl:34 on worker 70762
		</error>
	</testcase>
	<testcase name="Has retries=4 and always fails" timestamp="2023-06-28T15:27:20.358" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0x1f0aa0c1646351f8"></property>
		<property name="dd_tags[perf.bytes]" value="76694"></property>
		<property name="dd_tags[perf.allocs]" value="1171"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.0"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.002036292"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:37">Error in testset "Has retries=4 and always fails" on worker 70762:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:37
  Expression: false
Captured logs for test setup "StatefulSetup" (dependency of "Has retries=4 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 70762
These are the test setup logs.
No Captured Logs for test item "Has retries=4 and always fails" at test/testfiles/_retry_tests.jl:34 on worker 70762
		</error>
	</testcase>
	<testcase name="Has retries=4 and always fails" timestamp="2023-06-28T15:27:20.409" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0x1f0aa0c1646351f8"></property>
		<property name="dd_tags[perf.bytes]" value="76694"></property>
		<property name="dd_tags[perf.allocs]" value="1171"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.0"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.002146666"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:37">Error in testset "Has retries=4 and always fails" on worker 70762:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:37
  Expression: false
Captured logs for test setup "StatefulSetup" (dependency of "Has retries=4 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 70762
These are the test setup logs.
No Captured Logs for test item "Has retries=4 and always fails" at test/testfiles/_retry_tests.jl:34 on worker 70762
		</error>
	</testcase>
	<testcase name="Has retries=1 and always fails" timestamp="2023-06-28T15:27:20.411" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0xa6dc39304f36ff73"></property>
		<property name="dd_tags[perf.bytes]" value="76694"></property>
		<property name="dd_tags[perf.allocs]" value="1171"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="4.2e-8"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.001788791"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:43">Error in testset "Has retries=1 and always fails" on worker 70762:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:43
  Expression: false
Captured logs for test setup "StatefulSetup" (dependency of "Has retries=1 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 70762
These are the test setup logs.
No Captured Logs for test item "Has retries=1 and always fails" at test/testfiles/_retry_tests.jl:40 on worker 70762
		</error>
	</testcase>
	<testcase name="Has retries=1 and always fails" timestamp="2023-06-28T15:27:20.461" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0xa6dc39304f36ff73"></property>
		<property name="dd_tags[perf.bytes]" value="76694"></property>
		<property name="dd_tags[perf.allocs]" value="1171"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="1.25e-7"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.002127666"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:43">Error in testset "Has retries=1 and always fails" on worker 70762:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:43
  Expression: false
Captured logs for test setup "StatefulSetup" (dependency of "Has retries=1 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 70762
These are the test setup logs.
No Captured Logs for test item "Has retries=1 and always fails" at test/testfiles/_retry_tests.jl:40 on worker 70762
		</error>
	</testcase>
	<testcase name="Has retries=1 and always fails" timestamp="2023-06-28T15:27:20.512" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0xa6dc39304f36ff73"></property>
		<property name="dd_tags[perf.bytes]" value="76694"></property>
		<property name="dd_tags[perf.allocs]" value="1171"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.0"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.002010083"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:43">Error in testset "Has retries=1 and always fails" on worker 70762:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:43
  Expression: false
Captured logs for test setup "StatefulSetup" (dependency of "Has retries=1 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 70762
These are the test setup logs.
No Captured Logs for test item "Has retries=1 and always fails" at test/testfiles/_retry_tests.jl:40 on worker 70762
		</error>
	</testcase>
	<testcase name="Timeout always" timestamp="2023-06-28T15:27:20.514" time="20.016" tests="1" skipped="0" failures="0" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0xcf6065d51eaab366"></property>
		<property name="dd_tags[perf.bytes]" value="487748"></property>
		<property name="dd_tags[perf.allocs]" value="8937"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.006207959"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="20.010155125"></property>
		</properties>
	</testcase>
	<testcase name="Timeout first, pass after" timestamp="2023-06-28T15:27:40.532" time="20.048" tests="1" skipped="0" failures="0" errors="0">
		<properties>
		<property name="dd_tags[test.id]" value="0x728bfb311c0ec894"></property>
		<property name="dd_tags[perf.bytes]" value="3373762"></property>
		<property name="dd_tags[perf.allocs]" value="59584"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.028228625"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="20.020017167"></property>
		</properties>
	</testcase>
</testsuite>
</testsuites>